### ISSUE TITLE
Extension doesnt work in subscription-view again and shows just white window in config menu

### ISSUE THREAD

**Issue by chrischtea** [benjaminrubin/hider-chrome-extension-react#1]
When in subscription page (https://www.youtube.com/feed/subscriptions) Shorts are visible. Trying to access the config menu results in small white box instead of menu:
![grafik](https://github.com/user-attachments/assets/c32f4d90-fd57-4c2e-bf98-3155979a9311)
Was working fine yesterday.

Menu opens when in home page (https://www.youtube.com) as expected but when switching to a different tab (like Home Page, Search Page) in the extensions' settings menu same error occurs.
In home page no Shorts are visible as set up in the extension.

English 64-bit Chrome 127.0.6533.120 on German Windows 11 23H2.

right clicking the box and clicking Inspect reveals these errors in the console:
Settings.jsx:86 clickedPage subscriptionsPage
Settings.jsx:87 clickedPageSettings undefined
Settings.jsx:86 clickedPage subscriptionsPage
Settings.jsx:87 clickedPageSettings undefined
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'pageElements')
    at X (Settings.jsx:100:43)
    at Cl (react-dom.production.min.js:167:137)
    at xi (react-dom.production.min.js:197:258)
    at Cu (react-dom.production.min.js:292:88)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at yc (react-dom.production.min.js:280:180)
    at lc (react-dom.production.min.js:271:88)
    at ac (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
fi @ react-dom.production.min.js:189
react-dom.production.min.js:283 Uncaught TypeError: Cannot read properties of undefined (reading 'pageElements')
    at X (Settings.jsx:100:43)
    at Cl (react-dom.production.min.js:167:137)
    at xi (react-dom.production.min.js:197:258)
    at Cu (react-dom.production.min.js:292:88)
    at bc (react-dom.production.min.js:280:389)
    at vc (react-dom.production.min.js:280:320)
    at yc (react-dom.production.min.js:280:180)
    at lc (react-dom.production.min.js:271:88)
    at ac (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
36popup.html:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
2popup.html:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
18background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
2popup.html:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
background.js:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
background.js:251 pathnam is /@3DPrintStuff/videos
background.js:251 pathnam is /@3DPrintStuff/videos
background.js:251 pathnam is /@3DPrintStuff/videos
background.js:251 pathnam is /@DraftID/videos
background.js:251 pathnam is /@DraftID/videos
background.js:251 pathnam is /@DraftID/videos
background.js:251 pathnam is /@3DPrinterAcademy/videos
background.js:251 pathnam is /@3DPrinterAcademy/videos
background.js:251 pathnam is /@3DPrinterAcademy/videos
background.js:251 pathnam is /@PhilVandelay/videos
background.js:251 pathnam is /@PhilVandelay/videos
background.js:251 pathnam is /@PhilVandelay/videos
background.js:251 pathnam is /@NoEngineerHere/videos
background.js:251 pathnam is /@NoEngineerHere/videos
background.js:251 pathnam is /@NoEngineerHere/videos
background.js:251 pathnam is /@EngineeringAddiction/videos
background.js:251 pathnam is /@EngineeringAddiction/videos
background.js:251 pathnam is /@EngineeringAddiction/videos
background.js:251 pathnam is /playlist
background.js:251 pathnam is /playlist
background.js:251 pathnam is /playlist

**Comment by chrischtea** [comment]
looks like the new version fixed the issue!
thanks!
